### ISSUE TITLE
nano missing dependencies?

### ISSUE THREAD

**Issue by Jan-V2** [ivandavidov/minimal-linux-script#20]
so i tried to build the latest commit with just ncurses and nano.
however, when i try to run nano the following happens.

![emupng](https://user-images.githubusercontent.com/30025691/162617249-aac4f4cf-9885-4197-8190-ccba91d7416d.png)

it complains about missing a lib,, and when i check the /lib folder, it does 
the only thing i changed was that i added ncurses and nano as overlay packages
![config](https://user-images.githubusercontent.com/30025691/162617329-98baac00-a545-4f3b-aaaf-406535fbddd3.png)
i tried adding glibc_full to see if it would help but it didn't
besides in the documentation it states that it should automatically add dependencies.
so i think i might have found, a bug related to one of the dependencies.
correct me if i'm wrong of course, i'm still pretty new to this low level stuff.

**Comment by ivandavidov** [comment]
This issue is related to MLL, not to MLS.

I suggest you take a look at the [nano](https://github.com/ivandavidov/minimal/tree/master/src/minimal_overlay/bundles/nano) and [ncurses](https://github.com/ivandavidov/minimal/tree/master/src/minimal_overlay/bundles/ncurses) build processes and try to implement the solution proposed in [this thread](https://github.com/ivandavidov/minimal/issues/226). Unfortunately, I am too busy to maintain the dependencies, but I am open for pull requests.

Another option for you is to add the [static-get](https://github.com/ivandavidov/minimal#runtime-software) overlay bundle and install nano at runtime.
